### ISSUE TITLE
CloudQuery plugin is broken

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-cloudquery#10]
### Expected Behavior

List of issues that must be fixed:

- [x] no logo
- [x] documentation is misindented
- [ ] both tasks don't work on preview
- [ ] it doesn't work on M1/arm arch but this is a known issue related to Docker image and binary packaging

See flows:
- https://preview-oss.kestra.io/ui/executions/dev/cq_hn/nV5Not68ufWRWn8tNLsDK/logs?level=TRACE&page=1
- https://preview-oss.kestra.io/ui/executions/dev/cq_hn_cli/2OtMSjerqesONIePRy1YAk/logs

## Repro

This works perfectly fine:

```yaml
kind: source
spec:
  name: hackernews
  path: cloudquery/hackernews
  version: v3.0.13
  tables: ["*"]
  destinations: ["duckdb"]
  spec:
    item_concurrency: 100
    start_time: 2023-10-12T00:00:00Z
  # 90k rows for just 1 week of data
---
kind: destination
spec:
  name: duckdb
  path: cloudquery/duckdb
  version: "v4.2.10"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: hn.db
```

![image](https://github.com/kestra-io/plugin-cloudquery/assets/86264395/ebffb100-e663-4aba-9f72-a5defb4e638d)

Equivalent in kestra fails, see the links in the preview.

Sync:
![image](https://github.com/kestra-io/plugin-cloudquery/assets/86264395/40a47dd0-1136-4a25-8686-f73362e31772)

CLI:
![image](https://github.com/kestra-io/plugin-cloudquery/assets/86264395/a91a253a-7faa-4492-bfd0-c35790d2e83c)

### Environment Information

- Kestra Version: 0.13.0
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
