### ISSUE TITLE
Make the CloudQuery configs dynamic

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-cloudquery#27]
### Feature description

You'll get an error:

`Error: failed to sync v3 source hackernews: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: failed to validate spec: could not parse start_time: parsing time "{{ render(vars.start_date) }}" as "2006-01-02T15:04:05Z07:00": cannot parse "{{ render(vars.start_date) }}" as "2006"`

when trying to pass a start_date as dynamic variable coming from kestra's trigger.date

reproducer giving that error:

```yaml
id: cloudquery_sync
namespace: dev

variables: 
  start_date: |
    {{ trigger.date ?? execution.startDate | dateAdd(-1, "DAYS") | date("yyyy-MM-dd'T'HH:mm:ssXXX", timeZone="UTC") }}

tasks:
  - id: hn_to_duckdb
    type: io.kestra.plugin.cloudquery.Sync
    incremental: false
    outputFiles:
      - "*.csv"
    configs:
      - kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          registry: cloudquery
          version: v3.0.21
          tables: ["*"]
          destinations:
            - file
          spec:
            item_concurrency: 100
            start_time: "{{ render(vars.start_date) }}"
            # start_time: "2024-01-22T00:00:00Z"
      - kind: destination
        spec:
          name: file
          path: cloudquery/file
          version: v3.4.17
          spec:
            path: "{% raw %}{{TABLE}}/{{UUID}}.{{FORMAT}}{% endraw %}"
            format: csv
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "@daily"
    timezone: US/Eastern
```

Hardcoding the same string is working fine:

```yaml
id: cloudquery_sync
namespace: dev

tasks:
  - id: hn_to_duckdb
    type: io.kestra.plugin.cloudquery.Sync
    incremental: false
    outputFiles:
      - "*.csv"
    configs:
      - kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          registry: cloudquery
          version: v3.0.21
          tables: ["*"]
          destinations:
            - file
          spec:
            item_concurrency: 100
            start_time: "2024-01-22T00:00:00Z"
      - kind: destination
        spec:
          name: file
          path: cloudquery/file
          version: v3.4.17
          spec:
            path: "{% raw %}{{TABLE}}/{{UUID}}.{{FORMAT}}{% endraw %}"
            format: csv
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "@daily"
    timezone: US/Eastern
```
