### ISSUE TITLE
Allow loading CloudQuery plugins from Namespace Files or caching them

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-cloudquery#34]
### Feature description

User asked if there was a way to avoid the downloads every time they run the sync

Possible options:
- load from namespace files
- cache CQ plugins in internal storage using caching, similarly to WorkingDirectory caching

**Comment by anna-geller** [comment]
Closing as after recent changes on the CloudQuery side (ingestion framework is OSS but all plugins are proprietary and require an API key), it's no longer possible to download any plugins unless authorized with an API key

If you have an API key, you don't need to cache any local plugins.

Reproducer that will give you Unauthorized error:

```yaml
id: cloudquery_sync_hn_to_parquet
namespace: blueprint
description: unauthorized
tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    cache:
      ttl: PT1H
      patterns:
        - .cq/**
    tasks:
      - id: config
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          plugins.yml: |
            kind: source
            spec:
              name: hackernews
              path: cloudquery/hackernews
              version: v3.1.3
              tables: ["*"]
              destinations:
                - file
              spec:
                item_concurrency: 100
                start_time: "{{ execution.startDate | dateAdd(-1, 'DAYS') }}"
            ---
            kind: destination
            spec:
              name: file
              path: cloudquery/file
              version: v4.0.7
              spec:
                path: "{% raw %}{{TABLE}}/{{UUID}}.{{FORMAT}}{% endraw %}"
                format: parquet
          sync.yml: |
            kind: source
            spec:
              name: hackernews
              path: .cq/plugins/source/cloudquery/hackernews/v3.1.3
              version: v3.1.3
              tables: ["*"]
              destinations:
                - file
              spec:
                item_concurrency: 100
                start_time: "{{ execution.startDate | dateAdd(-1, 'DAYS') }}"
            ---
            kind: destination
            spec:
              name: file
              path: .cq/plugins/destination/cloudquery/file/v4.0.7
              version: v4.0.7
              spec:
                path: "{% raw %}{{TABLE}}/{{UUID}}.{{FORMAT}}{% endraw %}"
                format: parquet

      - id: get_plugins
        type: io.kestra.plugin.cloudquery.CloudQueryCLI
        commands:
          - cloudquery plugin install plugins.yml

      - id: hn_to_parquet
        type: io.kestra.plugin.cloudquery.CloudQueryCLI
        commands:
          - cloudquery sync sync.yml --log-console --log-level=warn
```
