### ISSUE TITLE
Tasks cannot run in Docker on M1

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-cloudquery#5]
### Expected Behavior

This will work just fine when running locally: `cloudquery sync hn_to_duckdb.yml`:

```yaml
kind: source
spec:
  name: hackernews
  path: cloudquery/hackernews
  version: v3.0.13
  tables: ["*"]
  backend_options:
    table_name: "cq_state"
    connection: "@@plugins.duckdb.connection"
  destinations:
    - "duckdb"
  spec:
    item_concurrency: 100
    start_time: 2023-10-09T00:00:00Z
---
kind: destination
spec:
  name: duckdb
  path: cloudquery/duckdb
  version: "v4.2.10"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: hn.db
```

But the kestra task is stuck after WARN log: `qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`

```yaml
id: cq_hn
namespace: dev

tasks:
  - id: hn
    type: io.kestra.plugin.cloudquery.Sync
    incremental: false
    configs: 
      - kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          version: v3.0.13
          tables: ["*"]
          destinations: ["duckdb"]
          spec:
            item_concurrency: 100
            start_time: 2023-10-09T00:00:00Z
          # 90k rows for just 1 week of data
      - kind: destination
        spec:
          name: duckdb
          path: cloudquery/duckdb
          version: "v4.2.10"
          write_mode: "overwrite-delete-stale"
          spec:
            connection_string: hn.db 
```

the same for CLI:

```yaml
id: cq_hn_cli
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: config
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          config.yml: |
            kind: source
            spec:
              name: hackernews
              path: cloudquery/hackernews
              version: v3.0.13
              tables: ["*"]
              backend_options:
                table_name: "cq_state"
                connection: "@@plugins.duckdb.connection"
              destinations:
                - "duckdb"
              spec:
                item_concurrency: 100
                start_time: 2023-10-09T00:00:00Z
            ---
            kind: destination
            spec:
              name: duckdb
              path: cloudquery/duckdb
              version: "v4.2.10"
              write_mode: "overwrite-delete-stale"
              spec:
                connection_string: hn.db

      - id: hn2
        type: io.kestra.plugin.cloudquery.CloudQueryCLI
        commands:
          - cloudquery sync config.yml
```

they keep running forever:

![image](https://github.com/kestra-io/plugin-cloudquery/assets/86264395/a53361d1-4094-4c66-9584-ea216aa94e4f)

### Environment Information

- Kestra Version: 0.13.0
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
fixed by CloudQuery by adding a dedicated image ghcr.io/cloudquery/cloudquery:latest-linux-arm64 here https://github.com/cloudquery/cloudquery/issues/14506#issuecomment-1764373170 

example of a working flow:

```yaml
id: cloudquery_sync
namespace: dev

tasks:
  - id: hn_to_duckdb
    type: io.kestra.plugin.cloudquery.Sync
    docker:
      image: ghcr.io/cloudquery/cloudquery:latest-linux-arm64
    incremental: false
    configs:
      - kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          version: v3.0.13
          tables: ["*"]
          destinations: ["file"]
          spec:
            item_concurrency: 100
            start_time: 2023-10-16T00:00:00Z
      - kind: destination
        spec:
          name: file
          path: cloudquery/file
          version: v3.4.8
          spec:
            path: "{% raw %}{{TABLE}}/{{UUID}}.{{FORMAT}}{% endraw %}"
            format: parquet
```
