### ISSUE TITLE
Basic sync doesn't work (unable to create the output directory)

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-cloudquery#82]
### Describe the issue

```yaml
id: test_cq
namespace: kestra

tasks:
  - id: hn_to_duckdb
    type: io.kestra.plugin.cloudquery.Sync
    env:
      CLOUDQUERY_API_KEY: "XXXX"
    incremental: false
    configs:
      - kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          version: v3.0.13
          tables: ["*"]
          destinations: ["duckdb"]
          spec:
            item_concurrency: 100
            start_time: "{{ now() | dateAdd(-1, 'DAYS') }}"
      - kind: destination
        spec:
          name: duckdb
          path: cloudquery/duckdb
          version: v4.2.10
          write_mode: overwrite-delete-stale
          spec:
            connection_string: hn.db
```

![image](https://github.com/user-attachments/assets/ab9a6ea3-4721-4263-88a3-4db07cbc6126)

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
no longer reproducing

best to validate that CQ works by using this flow with API key:

```yaml
id: cloudquery-sync-hn-to-parquet
namespace: company.team

tasks:
  - id: hn_to_parquet
    type: io.kestra.plugin.cloudquery.CloudQueryCLI
    inputFiles:
      config.yml: |
        kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          version: v3.7.7
          tables: ["*"]
          destinations:
            - file
          spec:
            item_concurrency: 100
            start_time: "{{ execution.startDate | dateAdd(-1, 'DAYS') }}"
        ---
        kind: destination
        spec:
          name: file
          path: cloudquery/file
          version: v5.4.6
          spec:
            path: "{% raw %}{{TABLE}}/{{UUID}}.{{FORMAT}}{% endraw %}"
            format: csv
    outputFiles:
      - "**/*.csv"
    env:
      CLOUDQUERY_API_KEY: xxx
    commands:
      - cloudquery sync config.yml --log-console --log-level=warn
```

shows on latest nicely that CSV files are in outputs correctly ✅
