### ISSUE TITLE
Sync report success but nothing happen

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-cloudquery#83]
### Describe the issue

The following flow doesn't work as expected

```yaml
id: hubspot
namespace: data.datasources

tasks:
  - id: sync
    type: io.kestra.plugin.cloudquery.Sync
    inputFiles:
      sa.json: "{{ render(namespace.gcp.serviceAccount) }}"
    env:
      CLOUDQUERY_API_KEY: "{{ secret('CLOUDQUERY_API_KEY') }}"
      HUBSPOT_APP_TOKEN: "{{ render(namespace.hubspot.accessToken) }}"
      GOOGLE_APPLICATION_CREDENTIALS: sa.json
    configs:
      - kind: destination
        spec:
          name: bigquery
          path: cloudquery/bigquery
          registry: cloudquery
          version: "v3.3.16"
          write_mode: "append"
          spec:
            project_id: kestra-prd
            dataset_id: hubspot
      - kind: source
        spec:
          name: hubspot
          path: cloudquery/hubspot
          registry: cloudquery
          version: "v3.0.18"
          destinations: ["bigquery"]
          tables: ["*"]
```
          spec:
            max_requests_per_second: 5
            table_options:
              hubspot_crm_companies:
                associations: []
                properties: []
              hubspot_crm_contacts:
                associations: []
                properties: []
              hubspot_crm_deals:
                associations: []
                properties: []
              hubspot_crm_line_items:
                associations: []
                properties: []
              hubspot_crm_products:
                associations: []
                properties: []
              hubspot_crm_quotes:
                associations: []
                properties: []
              hubspot_crm_tickets:
                associations: []
                properties: []
```

![image](https://github.com/user-attachments/assets/489139c0-5cce-4ac1-b05c-2e3c32190136)

As seen in the log, it reports SUCCESS state but not data has been processed.
The workaround for now is to use the CloudQueryCLI task:

```yaml
id: hubspot
namespace: data.datasources

tasks:
  - id: sync
    type: io.kestra.plugin.cloudquery.CloudQueryCLI
    allowWarning: true
    commands:
      - cloudquery sync config.yml --log-console
    env:
      CLOUDQUERY_API_KEY: "{{ secret('CLOUDQUERY_API_KEY') }}"
      HUBSPOT_APP_TOKEN: "{{ render(namespace.hubspot.accessToken) }}"
      GOOGLE_APPLICATION_CREDENTIALS: sa.json
    inputFiles:
      sa.json: "{{ render(namespace.gcp.serviceAccount) }}"
      config.yml: |
        kind: destination
        spec:
          name: bigquery
          path: cloudquery/bigquery
          registry: cloudquery
          version: "v4.2.2"
          write_mode: "append"
          spec:
            project_id: kestra-prd
            dataset_id: hubspot        
        ---
        kind: source
        spec:
          name: hubspot
          path: cloudquery/hubspot
          registry: cloudquery
          version: "v4.7.3"
          destinations: ["bigquery"]
          tables: ["*"]
          spec:
            max_requests_per_second: 5
            table_options:
              hubspot_crm_companies:
                associations: ["deal", "contact"]
                properties: ["numberofemployees", "country", "annualrevenue", "hs_industry_group", "industry", "type", "createdate", "domain", "hs_lastmodifieddate", "hs_object_id", "name"]
              hubspot_crm_contacts:
                associations: []
                properties: []
              hubspot_crm_deals:
                associations: []
                properties: []
              hubspot_crm_line_items:
                associations: []
                properties: []
              hubspot_crm_products:
                associations: []
                properties: []
              hubspot_crm_quotes:
                associations: []
                properties: []
              hubspot_crm_tickets:
                associations: []
                properties: []        
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 6 * * *
```
which run things properly as we can see in the logs below:
![image](https://github.com/user-attachments/assets/7c6f02ee-be36-4213-9c45-01363e8bfe58)

### Environment

- Kestra Version: develop

**Comment by Ben8t** [comment]
I'm still able to reproduce. Here is a full reproducer (duckdb destination is a bit tricker to test, I'm using file destination instead). First task is very fast, too fast compared to second task that actually download source and expose files (see outputFiles)

```yaml
id: cloudquery-synctest
namespace: company.team

variables:
  test: path/to/files/{{TABLE}}/{{UUID}}.{{FORMAT}}

tasks:
  - id: hn_to_duckdb
    type: io.kestra.plugin.cloudquery.Sync
    env:
      CLOUDQUERY_API_KEY: "cqtk_KhHfJi2OY8ESaOC3xITSBN33Tnzsyme9"
    incremental: false
    configs:
      - kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          version: v3.7.7
          tables:
            - "*"
          destinations:
            - file
          spec:
            item_concurrency: 100
            start_time: "{{ trigger.date ?? execution.startDate | dateAdd(-1, 'DAYS') }}"
      - kind: destination
        spec:
          name: "file"
          path: "cloudquery/file"
          registry: "cloudquery"
          version: "v5.4.6"
          write_mode: "append"
          # Learn more about the configuration options at https://cql.ink/file_destination
          spec:
            path: "{{ vars.test }}"
            format: "csv"


  - id: sync
    type: io.kestra.plugin.cloudquery.CloudQueryCLI
    taskRunner:
      entryPoint: []
      type: io.kestra.plugin.scripts.runner.docker.Docker
    allowWarning: true
    commands:
      - cloudquery sync config.yml --log-console
    env:
      CLOUDQUERY_API_KEY: "cqtk_KhHfJi2OY8ESaOC3xITSBN33Tnzsyme9"
    outputFiles:
      - path/to/files/**/*.csv
    inputFiles:
      config.yml: |
        kind: source
        spec:
          name: hackernews
          path: cloudquery/hackernews
          version: v3.7.7
          tables:
            - "*"
          destinations:
            - file
          spec:
            item_concurrency: 100
            start_time: "{{ trigger.date ?? execution.startDate | dateAdd(-1, 'DAYS') }}"
        ---
        kind: destination
        spec:
          name: "file"
          path: "cloudquery/file"
          registry: "cloudquery"
          version: "v5.4.6"
          write_mode: "append"
          # Learn more about the configuration options at https://cql.ink/file_destination
          spec:
            path: "{{ vars.test }}"
            format: "csv"  
```

Execution example can be find here: https://postgres-oss.preview.dev.kestra.io/ui/executions/company.team/cloudquery-synctest/1GZPwwIpF48lwFurrRqbUc/gantt
